### ISSUE TITLE
new release for world airliners set

### ISSUE THREAD

**Issue by Bassemtellawi** [RvP93/WorldAirlinersSet#26]
Hello will the future releases for world airliners set will be posted here ? will there be any new releases soon ? Just a request and suggestion, please add Turkish Airlines current fleet livery and Egypt Air B787-9 , A220 with Middle East Airlines A321neo and A330-200. I saw some MEA, Kuwait Airways and Sabena A310-300 please add them to be available in the future release. Thank You .

**Comment by RvP93** [comment]
Hi, I aim to have it released here indeed. Still trying to figure out how this works so there will no new release soon.
Regarding your request I strongly recommend to make it youself because if it's set up correctly will first be working on v1.0.
Cheers Rens

**Comment by Bassemtellawi** [comment]
Thank you so much for your reply and best of luck 🙏🙏

**Comment by RvP93** [comment]
Hi, atm there is no time frame. We first need to get the system back up and running which transfers the actual code to the file you can drop in OpenTTD to get playing. Some good people are working on it but it will take time.
Thanks for your compliments :)

**Comment by Bassemtellawi** [comment]
Thank you so much and best of luck.

Regards,

Bassem
