### ISSUE TITLE
NewGRF based on WAS

### ISSUE THREAD

**Issue by GBLINER** [RvP93/WorldAirlinersSet#28]
Hello, I am making New GRF Korean Airliners Set. We are making the sprite based on WAS. Is it possible to use the sprite of WAS? It uses GPLv3, the same copyright as WAS. It will also indicate the source.

**Comment by RvP93** [comment]
Hi, Sure but that means you can contribute to the WAS too right? Would love to add all the airlines from Korea as well in the WAS.
Make sure to also ask permission from PikkaBird as most of the sprites come from the Av8 set.
