### ISSUE TITLE
747 sprite suggestions

### ISSUE THREAD

**Issue by RetroAviator** [RvP93/WorldAirlinersSet#29]
Hello! I've made a couple of Philippine Airlines sprites for 747s (-200B and -400) in the Sunriser livery. Is there a place to post livery suggestion sprites for possible inclusion into WAS? Thanks in advance!

![PAL_747-200B-v2](https://user-images.githubusercontent.com/113995267/191261590-ad0a6218-edab-4a3f-b193-24c873b99bb4.png)

![PAL_747-400](https://user-images.githubusercontent.com/113995267/191261613-14cf5ac4-d901-4a70-b321-5d2854532b20.png)

**Comment by RvP93** [comment]
Hi,

First of all, thanks for your contribution!
I've added it to my to-do list.

You can find all posts on our forum on
https://worldairlinerset.forumotion.net/

Cheers,
Rens


Op di 20 sep. 2022 om 14:51 schreef RetroAviator ***@***.***>:

**Comment by RetroAviator** [comment]
You're welcome! Looking forward to seeing them in a future version.

I'll repost the sprites to the forum. Thank you!
