### ISSUE TITLE
MEA A310 late 90's livery 

### ISSUE THREAD

**Issue by Bassemtellawi** [RvP93/WorldAirlinersSet#30]
Hello I made MEA A310-200 in late 90's livery. Is it possible that someone code it and add it ? Thank you 
![MEAA310-200_034136 (1)](https://user-images.githubusercontent.com/100780889/193758351-aebb0aea-c29f-4806-9efc-1eca9c050387.png)

**Comment by RvP93** [comment]
Hi Basem,

I've added it to my todo list.

**Comment by Bassemtellawi** [comment]
Thank you I will try to add more in my spare time :)
