### ISSUE TITLE
Turkish Airlines 737max8 

### ISSUE THREAD

**Issue by Bassemtellawi** [RvP93/WorldAirlinersSet#31]

**Comment by RvP93** [comment]
Hi Bassem,

Added to my to do list.
Possible to upload all new paint to the WAS Forum on https://worldairlinerset.forumotion.net/ ?

**Comment by Bassemtellawi** [comment]
> Hi Bassem,
> 
> Added to my to do list. Possible to upload all new paint to the WAS Forum on https://worldairlinerset.forumotion.net/ ?

Well noted thank you

**Comment by Bassemtellawi** [comment]
When the next update is estimated to be released?

**Comment by Bassemtellawi** [comment]
Hello I have added 6 liveries until now and more to come and I uploaded them in the was forum. Will they be added in the next release? Thank you
